# Generated by Django 5.2.17 on 2026-10-02 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_roupas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrinho', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='loja_roupas.carrinho')),
                ('roupa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_em_carrinhos', to='loja_roupas.roupa')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('carrinho', 'roupa'), name='unq_roupa_por_carrinho'), models.CheckConstraint(condition=models.Q(('quantidade__gte', 1)), name='item_carrinho_quantidade_minima_1')],
            },
        ),
    ]
