# Generated by Django 5.2.17 on 2026-10-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_roupas', '0003_criar_carrinhos_para_usuarios_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='roupa',
            name='imagem',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
